# Minimal integration for an existing CMake project that already owns its
# executable targets. Include this after the target declarations.
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/FaultDebugSelective.cmake")

function(faultdebug_instrument_existing target)
  if(NOT TARGET ${target})
    message(FATAL_ERROR "faultdebug_instrument_existing: unknown target ${target}")
  endif()
  if(TARGET faultdebug_runtime)
    target_link_libraries(${target} PRIVATE faultdebug_runtime)
    set_property(TARGET ${target} APPEND PROPERTY BUILD_RPATH "$<TARGET_FILE_DIR:faultdebug_runtime>")
  elseif(FAULTDEBUG_RUNTIME_DIR)
    target_link_directories(${target} PRIVATE "${FAULTDEBUG_RUNTIME_DIR}")
    target_link_libraries(${target} PRIVATE faultdebug_runtime)
    set_property(TARGET ${target} APPEND PROPERTY BUILD_RPATH "${FAULTDEBUG_RUNTIME_DIR}")
  else()
    message(FATAL_ERROR "Define FAULTDEBUG_RUNTIME_DIR or provide a faultdebug_runtime target")
  endif()
  faultdebug_apply_source_filters(${target})
  target_link_options(${target} PRIVATE -Wl,--build-id=sha1)
  set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "Export compilation database" FORCE)
endfunction()

function(faultdebug_instrument_existing_tree)
  if(NOT DEFINED FAULTDEBUG_RUNTIME_DIR)
    set(FAULTDEBUG_RUNTIME_DIR "" CACHE PATH "Directory containing libfaultdebug_runtime.so")
  endif()
  message(STATUS "faultdebug legacy integration: call faultdebug_instrument_existing(target) for each executable")
endfunction()
